project_id = "rdrcqtjlveoygzwvbsmd"

[functions.send-email]
verify_jwt = false

[functions.video-clip-advisor]
verify_jwt = false

[functions.create-recruiting-payment]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.create-expense-payment]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false
